# Generated by Django 3.1.1 on 2020-09-18 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0002_auto_20200918_1602'),
    ]

    operations = [
        migrations.AlterField(
            model_name='examscore',
            name='score',
            field=models.IntegerField(default=0, verbose_name=range(1, 100)),
        ),
    ]
