# Generated by Django 3.1.1 on 2020-09-21 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0003_auto_20200918_1604'),
    ]

    operations = [
        migrations.AlterField(
            model_name='examscore',
            name='subject',
            field=models.CharField(choices=[('math', 'คณิตศาสตร์'), ('sci', 'วิทยาศาสตร์'), ('art', 'ศิลปะ'), ('eng', 'ภาษาอังกฤษ')], default='math', max_length=200),
        ),
    ]
