# Generated by Django 3.1.1 on 2020-09-21 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0004_auto_20200921_1627'),
    ]

    operations = [
        migrations.AlterField(
            model_name='examscore',
            name='subject',
            field=models.CharField(choices=[('math', 'คณิตศาสตร์'), ('sci', 'วิทยาศาสตร์'), ('eng', 'ภาษาอังกฤษ'), ('bio', 'ชีววิทยา')], default='math', max_length=200),
        ),
    ]
