# Generated by Django 3.1.1 on 2020-10-08 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0006_supplies_fict'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplies_fict',
            name='location',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
