# Generated by Django 3.1.1 on 2020-10-08 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0007_supplies_fict_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplies_fict',
            name='sup_img',
            field=models.ImageField(blank=True, default='default.png', null=True, upload_to='supplies_img'),
        ),
    ]
