# Generated by Django 3.1.2 on 2020-10-09 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0008_supplies_fict_sup_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplies_fict',
            name='orgs',
            field=models.IntegerField(choices=[('ส่วนภูมิภาค', ((99, 'เลือกหน่วยงาน'), (0, 'สำนักจัดการทรัพยากรป่าไม้ที่ 1 (เชียงใหม่)'), (1, 'สำนักจัดการทรัพยากรป่าไม้ที่ 1 สาขาแม่ฮ่องสอน'), (2, 'สำนักจัดการทรัพยากรป่าไม้ที่ 2 (เชียงราย)'), (3, 'สำนักจัดการทรัพยากรป่าไม้ที่ 3 (ลำปาง)'), (4, 'สำนักจัดการทรัพยากรป่าไม้ที่ 3 สาขาแพร่'), (5, 'สำนักจัดการทรัพยากรป่าไม้ที่ 4 (ตาก)'), (6, 'สำนักจัดการทรัพยากรป่าไม้ที่ 4 สาขานครสวรรค์'), (7, 'สำนักจัดการทรัพยากรป่าไม้ที่ 4 สาขาพิษณุโลก'), (8, 'สำนักจัดการทรัพยากรป่าไม้ที่ 5 (สระบุรี)'), (9, 'สำนักจัดการทรัพยากรป่าไม้ที่ 6 (อุดรธานี)'), (10, 'สำนักจัดการทรัพยากรป่าไม้ที่ 6 สาขานครพนม'), (11, 'สำนักจัดการทรัพยากรป่าไม้ที่ 7 (ขอนแก่น)'), (12, 'สำนักจัดการทรัพยากรป่าไม้ที่ 7 สาขาอุบลราชธานี'), (13, 'สำนักจัดการทรัพยากรป่าไม้ที 8 (นครราชสีมา)'), (14, 'สำนักจัดการทรัพยากรป่าไม้ที่ 9 (ชลบุรี)'), (15, 'สำนักจัดการทรัพยากรป่าไม้ที่ 9 สาขาปราจีนบุรี'), (16, 'สำนักจัดการทรัพยากรป่าไม้ที่ 10 (ราชบุรี)'), (17, 'สำนักจัดการทรัพยากรป่าไม้ที่ 10 สาขาเพชรบุรี'), (18, 'สำนักจัดการทรัพยากรป่าไม้ที่ 11 (สุราษฎร์ธานี)'), (19, 'สำนักจัดการทรัพยากรป่าไม้ที่ 12 (นครศรีธรรมราช)'), (20, 'สำนักจัดการทรัพยากรป่าไม้ที่ 12 สาขากระบี่'), (21, 'สำนักจัดการทรัพยากรป่าไม้ที่ 13 (สงขลา)'), (22, 'สำนักจัดการทรัพยากรป่าไม้ที่ 13 สาขานราธิวาส'))), ('ส่วนกลาง', ((23, 'สำนักกฎหมาย'), (24, 'สำนักการอนุญาต'), (25, 'สำนักบริหารกลาง'), (26, 'สำนักจัดการป่าชุมชน'), (27, 'สำนักจัดการที่ดินป่าไม้'), (28, 'สำนักส่งเสริมการปลูกป่า'), (29, 'สำนักเศรษฐกิจการป่าไม้'), (30, 'สำนักการป่าไม้ต่างประเทศ'), (31, 'สำสำนักแผนงานและสารสนเทศ'), (32, 'สำนักวิจัยและพัฒนาการป่าไม้'), (33, 'สำนักป้องกันรักษาป่าและควบคุมไฟป่า'), (34, 'สำนักโครงการพระราชดำริและกิจการพิเศษ'), (35, 'กลุ่มตรวจสอบภายใน'), (36, 'กลุ่มพัฒนาระบบบริหาร'), (37, 'กลุ่มงานคุ้มครองจริยธรรมกรมป่าไม้'), (38, 'ศูนย์เทคโนโลยีสารสนเทศและการสื่อสาร')))], default=99, max_length=100, verbose_name='หน่วยงาน'),
        ),
        migrations.AlterField(
            model_name='supplies_fict',
            name='acquisition_type',
            field=models.IntegerField(choices=[(0, 'ได้รับจัดสรรตามปีงบประมาณ'), (1, 'เช่าซื้อ/บริจาค')], default=0, max_length=100, verbose_name='วีธีการได้มา'),
        ),
        migrations.AlterField(
            model_name='supplies_fict',
            name='brand_name',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='ยี่ห้อ/รุ่น'),
        ),
        migrations.AlterField(
            model_name='supplies_fict',
            name='date_recive',
            field=models.IntegerField(blank=True, max_length=4, null=True, verbose_name='ปีที่ได้รับ'),
        ),
        migrations.AlterField(
            model_name='supplies_fict',
            name='location',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='ที่ตั้ง ส่วน/ฝ่าย'),
        ),
        migrations.AlterField(
            model_name='supplies_fict',
            name='org_number',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='เลขครุภัณฑ์ (ปม)'),
        ),
        migrations.AlterField(
            model_name='supplies_fict',
            name='other',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='หมายเหตุ'),
        ),
        migrations.AlterField(
            model_name='supplies_fict',
            name='serial_number',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='หมายเลขเครื่อง (S/N)'),
        ),
        migrations.AlterField(
            model_name='supplies_fict',
            name='status_sup',
            field=models.IntegerField(choices=[(0, 'ดี'), (1, 'ชำรุด'), (2, 'เสีย'), (3, 'รอจำหน่าย')], default=0, max_length=100, verbose_name='สถานะ'),
        ),
        migrations.AlterField(
            model_name='supplies_fict',
            name='sup_img',
            field=models.ImageField(blank=True, default='default.png', null=True, upload_to='supplies_img', verbose_name='รูปครุภัณฑ์'),
        ),
        migrations.AlterField(
            model_name='supplies_fict',
            name='supplies_type',
            field=models.IntegerField(choices=[(0, 'คอมพิวเตอร์ตั้งโต๊ะ'), (1, 'คอมพิวเตอร์พกพา'), (2, 'เครื่องสำรองไฟ'), (3, 'เครื่องพิมพ์ ขาวดำ LED'), (4, 'เครื่องพิมพ์ สี LED'), (5, 'เครื่องสแกน Scanner')], default=0, max_length=100, verbose_name='รายการครุภัณฑ์'),
        ),
    ]
