# Generated by Django 4.0.5 on 2022-06-14 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Supplies_fict',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('supplies_type', models.IntegerField(choices=[(0, 'คอมพิวเตอร์ตั้งโต๊ะ'), (1, 'คอมพิวเตอร์พกพา'), (2, 'เครื่องสำรองไฟ'), (3, 'เครื่องพิมพ์ ขาวดำ LED'), (4, 'เครื่องพิมพ์ สี LED'), (5, 'เครื่องสแกน Scanner')], default=0, max_length=100)),
                ('brand_name', models.CharField(blank=True, max_length=200, null=True)),
                ('org_number', models.CharField(blank=True, max_length=200, null=True)),
                ('serial_number', models.CharField(blank=True, max_length=200, null=True)),
                ('date_recive', models.IntegerField(blank=True, max_length=4, null=True)),
                ('acquisition_type', models.IntegerField(choices=[(0, 'ได้รับจัดสรรตามปีงบประมาณ'), (1, 'เช่าซื้อ/บริจาค')], default=0, max_length=100)),
                ('status_sup', models.IntegerField(choices=[(0, 'ดี'), (1, 'ชำรุด'), (2, 'เสีย'), (3, 'รอจำหน่าย')], default=0, max_length=100)),
                ('location', models.CharField(blank=True, max_length=200, null=True)),
                ('other', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
    ]
